### PR TITLE
MODE_NONE on Fedora - fixes and default

### PR DESCRIPTION
**Pull request by samdroid-apps**
This replaces https://github.com/sugarlabs/sugar-docs/pull/78

### CODE REVIEW

**Comment by dhanvi** [comment]
I am getting the following error when I use this branch, I might want to use the original one for now

```bash
[c0mrad3@localhost sugar-build]$ ./osbuild pull 

= Setup the build system =

* Create the python virtualenv
* Install python packages
remote: Counting objects: 979, done.
remote: Total 979 (delta 0), reused 0 (delta 0), pack-reused 979
Receiving objects: 100% (979/979), 170.16 KiB | 55.00 KiB/s, done.
Resolving deltas: 100% (585/585), done.
Command /home/c0mrad3/sugar-build/build/out/sandbox/install/bin/python2.7 -c "import setuptools, tokenize;__file__='/home/c0mrad3/sugar-build/build/out/sandbox/install/build/sourcestamp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-N5lSw_-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/c0mrad3/sugar-build/build/out/sandbox/install/include/site/python2.7 failed with error code 1 in /home/c0mrad3/sugar-build/build/out/sandbox/install/build/sourcestamp
Storing debug log for failure in /home/c0mrad3/.pip/pip.log
Traceback (most recent call last):
  File "./osbuild", line 484, in <module>
    if not main():
  File "./osbuild", line 463, in main
    if not setup(options.command):
  File "./osbuild", line 300, in setup
    raise e
subprocess.CalledProcessError: Command '['/home/c0mrad3/sugar-build/build/out/sandbox/install/bin/pip', '-q', 'install', 'git+https://github.com/dnarvaez/osbuild', 'sourcestamp']' returned non-zero exit status 1
```

**Comment by samdroid-apps** [comment]
@i5o just brought up the pip error on irc.  Seems to be due to an undeclared dep of `python-devel`.

**Comment by samdroid-apps** [comment]
Sorry, it is marked as a dep.  But osbuild installs pip packages *before* the system packages, which is kinda bad since pip needs the system packages.  Maybe that should be reversed?

**Comment by i5o** [comment]
Also, gcc in case you don't have it.

`sudo dnf install gcc python-devel`

Anyway, I got
`gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No existe el fichero o el directorio` (trans: File not found, or whatever like that in English)

**Comment by i5o** [comment]
Package: redhat-rpm-config solved it

**Comment by samdroid-apps** [comment]
Ok, I've pushed changes that should fix that

**Comment by samdroid-apps** [comment]
15:58 <ignacio> now I can't build sugar-web
15:58 <ignacio> agh
15:59 <ignacio> sugar-web: http://fpaste.org/277412/14444531/
16:01 <ignacio> sudo npm install -g volo
16:02 <ignacio> samdroid, I think the npm_packages aren't being installed by default

There is no mention of "node" or "npm" in osbuild, so I think @i5o is right.

**Comment by samdroid-apps** [comment]
Just forced pushed some changed.  I fixed the issue where it would try to install everything from dnf every single osbuild run.

**Comment by i5o** [comment]
Just installed F24 (a live image with XFCE Spin)
will try this with the normal packages installed (the system ones that comes by default).

**Comment by i5o** [comment]
The system asks me if I want to install the packages

We should do:
dnf -y
or yum -y
instead of ask the user

**Comment by i5o** [comment]
./osbuild pull 
http://paste.fedoraproject.org/285894/30024144

Will continue with run

**Comment by samdroid-apps** [comment]
That's all fine right?

**Comment by i5o** [comment]
Yep, will test in few minutes the run

**Comment by i5o** [comment]
Can't build.

http://fpaste.org/286119/64809391/

**Comment by i5o** [comment]
Trying to:
[tamara@tamara-laptop sugar-build]$ mkdir -p build/out/install/etc/gconf/

and then build

**Comment by i5o** [comment]
tadaaaa!
* Building sugar
* Building sugar-artwork
* Building sugar-datastore
* Building sugar-runner

until
* Building sugar-web *ERROR* 

http://fpaste.org/286125/64814971/

[tamara@tamara-laptop sugar-build]$ sudo npm install -g volo

we should install the npm packages automatically

[tamara@tamara-laptop sugar-build]$ ./osbuild build

= Building =

* Building sugar-web
* Building sugar-web-test
* Building sugar-web-template
* Building docker
* Building browse
* Building write
* Building chat
* Building read
* Building log
* Building terminal
* Building pippy
* Building imageviewer
* Building jukebox
* Building turtleart
* Building clock-web
* Building gtd-activity
[tamara@tamara-laptop sugar-build]$ 
*Success*

**Comment by i5o** [comment]
wooooooooow. This is regression.
captura de pantalla_2015-11-02_13-34-22

**Comment by samdroid-apps** [comment]
Is this ok?  Can we merge this @i5o?

**Comment by i5o** [comment]
This worked in fedora.

I will test if this doesnt work support for Ubuntu (sounds stupid, but
well. I will test)

2015-11-13 19:14 GMT-03:00, Sam <notifications@github.com>:
> Is this ok?  Can we merge this @i5o?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sugarlabs/sugar-build/pull/31#issuecomment-156573961


-- 
Ignacio Rodríguez
SugarLabs at Facebook
<https://www.facebook.com/pages/SugarLabs/187845102582>

**Comment by i5o** [comment]
Something is broken with ubuntu (USing ubuntu 16.04, I can't even pull with
your version, or with the withoutchanges version)

But I will merge this one because it's works on fedora.

Ignacio Rodríguez
SugarLabs at Facebook
<https://www.facebook.com/pages/SugarLabs/187845102582>

2015-11-13 19:20 GMT-03:00 Ignacio Rodríguez <ignacio@sugarlabs.org>:

**Comment by i5o** [comment]
Nevermind, just saw tch comment.

Here is what I did in ubuntu and got a error
```
ignacio@ignacio-pc:~/Escritorio$ git clone git://github.com/samdroid-apps/sugar-build
Clonar en «sugar-build»...
remote: Counting objects: 6606, done.
remote: Total 6606 (delta 0), reused 0 (delta 0), pack-reused 6606
Receiving objects: 100% (6606/6606), 1.18 MiB | 488.00 KiB/s, done.
Resolving deltas: 100% (3282/3282), done.
Checking connectivity... hecho.
ignacio@ignacio-pc:~/Escritorio$ cd sugar-build/
ignacio@ignacio-pc:~/Escritorio/sugar-build$ ls
activities  build  osbuild  README.md
ignacio@ignacio-pc:~/Escritorio/sugar-build$ ./osbuild pull

= Setup the host build system =

* Create the python virtualenv
Traceback (most recent call last):
  File "/home/ignacio/Escritorio/sugar-build/build/out/sandbox-host/cache/virtualenv-1.11.4/virtualenv.py", line 2338, in <module>
    main()
  File "/home/ignacio/Escritorio/sugar-build/build/out/sandbox-host/cache/virtualenv-1.11.4/virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "/home/ignacio/Escritorio/sugar-build/build/out/sandbox-host/cache/virtualenv-1.11.4/virtualenv.py", line 992, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/home/ignacio/Escritorio/sugar-build/build/out/sandbox-host/cache/virtualenv-1.11.4/virtualenv.py", line 960, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/home/ignacio/Escritorio/sugar-build/build/out/sandbox-host/cache/virtualenv-1.11.4/virtualenv.py", line 902, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/ignacio/Escrit...nstall/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
Traceback (most recent call last):
  File "./osbuild", line 488, in <module>
    if not main():
  File "./osbuild", line 467, in main
    if not setup(options.command):
  File "./osbuild", line 305, in setup
    raise e
subprocess.CalledProcessError: Command '['python2.7', '/home/ignacio/Escritorio/sugar-build/build/out/sandbox-host/cache/virtualenv-1.11.4/virtualenv.py', '-q', '--system-site-packages', '/home/ignacio/Escritorio/sugar-build/build/out/sandbox-host/install']' returned non-zero exit status 1
ignacio@ignacio-pc:~/Escritorio/sugar-build$ cd ..
ignacio@ignacio-pc:~/Escritorio$ git clone git://github.com/sugarlabs/sugar-build sugar-build-
Clonar en «sugar-build-»...
remote: Counting objects: 6592, done.
remote: Total 6592 (delta 0), reused 0 (delta 0), pack-reused 6592
Receiving objects: 100% (6592/6592), 1.17 MiB | 398.00 KiB/s, done.
Resolving deltas: 100% (3272/3272), done.
Checking connectivity... hecho.
ignacio@ignacio-pc:~/Escritorio$ cd sugar-build-
ignacio@ignacio-pc:~/Escritorio/sugar-build-$ ls
activities  build  osbuild  README.md
ignacio@ignacio-pc:~/Escritorio/sugar-build-$ ./osbuild pull

= Setup the host build system =

* Create the python virtualenv
Traceback (most recent call last):
  File "/home/ignacio/Escritorio/sugar-build-/build/out/sandbox-host/cache/virtualenv-1.11.4/virtualenv.py", line 2338, in <module>
    main()
  File "/home/ignacio/Escritorio/sugar-build-/build/out/sandbox-host/cache/virtualenv-1.11.4/virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "/home/ignacio/Escritorio/sugar-build-/build/out/sandbox-host/cache/virtualenv-1.11.4/virtualenv.py", line 992, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/home/ignacio/Escritorio/sugar-build-/build/out/sandbox-host/cache/virtualenv-1.11.4/virtualenv.py", line 960, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/home/ignacio/Escritorio/sugar-build-/build/out/sandbox-host/cache/virtualenv-1.11.4/virtualenv.py", line 902, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/ignacio/Escrit...nstall/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
Traceback (most recent call last):
  File "./osbuild", line 488, in <module>
    if not main():
  File "./osbuild", line 467, in main
    if not setup(options.command):
  File "./osbuild", line 305, in setup
    raise e
subprocess.CalledProcessError: Command '['python2.7', '/home/ignacio/Escritorio/sugar-build-/build/out/sandbox-host/cache/virtualenv-1.11.4/virtualenv.py', '-q', '--system-site-packages', '/home/ignacio/Escritorio/sugar-build-/build/out/sandbox-host/install']' returned non-zero exit status 1
ignacio@ignacio-pc:~/Escritorio/sugar-build-$ 
```

**Comment by tchx84** [comment]
I tested it, works fine, but please see the comments I left.

**Comment by i5o** [comment]
Did you tested in Ubuntu?

**Comment by tchx84** [comment]
Only in Fedora 23...

Also, strangely I didn't get the volo error while building sugar-web... I used to get that error... In any case maybe we should have a copy (of osbuild [1] in sugarlabs github page.

[1] https://github.com/dnarvaez/osbuild

**Comment by samdroid-apps** [comment]
Thanks for the review @tchx84, I made the changes and added them as another commit (9690b23) to the branch.  Please pull and merge if they're ok!

I don't understand what dnarvaez/osbuild is.  The commands are already part of this repo <https://github.com/sugarlabs/sugar-build/tree/master/build/commands>.  Is his version for CI testing?

Ubuntu seems messed up.  Maybe we should get a list of packages like we have for fedora but on ubuntu?

**Comment by i5o** [comment]
Yeah, we need to so something similar like this for Ubuntu.
I think we need to fix that bug "critical" (maybe it's only on 16.04!) ASAP (before GCI)

**Comment by samdroid-apps** [comment]
good idea.  Are you running ubuntu now @i5o?  If you can find a list of pacakges that you need to install sugar-build in MODE_NONE on ubuntu then we could make a patch.  Otherwise, I'll have a go in a vm.

Also 16.04?  Isn't that for 2016?

**Comment by i5o** [comment]
It's the rawhide of Ubuntu :P

I don't have 15.10 right now (i'm not sure if I tested this before
upgrade, but I think it failed too)

2015-11-14 1:50 GMT-03:00, Sam <notifications@github.com>:
> good idea.  Are you running ubuntu now @i5o?  If you can find a list of
> pacakges that you need to install sugar-build in MODE_NONE on ubuntu then we
> could make a patch.  Otherwise, I'll have a go in a vm.
>
> Also 16.04?  Isn't that for 2016?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sugarlabs/sugar-build/pull/31#issuecomment-156628229


-- 
Ignacio Rodríguez
SugarLabs at Facebook
<https://www.facebook.com/pages/SugarLabs/187845102582>

**Pull request merged**
