### PR TITLE
Fix broot mode consistency

### PR DESCRIPTION
**Pull request by tchx84**

### CODE REVIEW

**Comment by tchx84** [comment]
Note that, to produce the bug, you must run sugar-build on Fedora without the prefs.json file (and wihtout use_broot entry)

If the prefs file has the "use_broot" entry, then is consistent, BUT, the bug occurs when it does not contain that entry and each script uses a different "default".

**Comment by godiard** [comment]
Looks good

**Comment by tchx84** [comment]
@walterbender @godiard @samdroid-apps can any of you test and merge it? :)

**Comment by samdroid-apps** [comment]
Looks great, I'm away from my computer though.  Please feel free to merge.

**Pull request merged**
